### ISSUE TITLE
Could we make napari compatible with annotating 3D tiffs?  Example images located here: \\allen\aics\assay-dev\MicroscopyData\Melissa\2019\20190412\napari  

### ISSUE THREAD

**Issue by kaytlyng** [AllenCellModeling/napari#2]
## 🐛 Bug

Could we make napari compatible with annotating 3D tiffs?  We've used it successfully for 3D myulti-channel .czi files, and also for 2D multi-channel tiffs. We'd like this to work with 3D multichannel tiffs. Example images located here: \\allen\aics\assay-dev\MicroscopyData\Melissa\2019\20190412\napari  

## To Reproduce

1.  Run napari using the .json file attached calling the attached .csv file
2. Image loads into napari, but the z-level slide bar does not work

json: 
{
	"annotator": "kg",
	"data_csv": "./data/napari_ACTN2.csv",
	"data_dir_local": "/Volumes/fish_usb/ACTN2",
	"save_dir": "/Volumes/fish_usb/ACTN2/annotationsACTN2",
	"start_from_last_annotation": 1,
	"save_if_empty": 0
}

csv: 

file_path | set | probe488 | probe561 | probe638
-- | -- | -- | -- | --
/Volumes/fish_usb/ACTN2/M01_001-Position80_XY1555103544_Z00_T0_C4.tif | reference | structure | MYH6 | MYH7
/Volumes/fish_usb/ACTN2/M01_001-Position81_XY1555103545_Z00_T0_C4.tif | reference | structure | MYH6 | MYH7
/Volumes/fish_usb/ACTN2/M01_001-Position82_XY1555103546_Z00_T0_C4.tif | reference | structure | MYH6 | MYH7
/Volumes/fish_usb/ACTN2/M01_001-Position83_XY1555103547_Z00_T0_C4.tif | reference | structure | MYH6 | MYH7
/Volumes/fish_usb/ACTN2/M01_001-Position84_XY1555103548_Z00_T0_C4.tif | reference | structure | MYH6 | MYH7

**Comment by gregjohnso** [comment]
Resolved with commit df4bb09
